// Auto-generated by generate_gallery.py. Re-run the script to update.
window.QUILTS = {
  "A": [
    {
      "file": "images/A1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "B": [
    {
      "file": "images/B1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/B2.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "C": [
    {
      "file": "images/C1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/C2.mp4",
      "type": "video",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/C3.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "D": [
    {
      "file": "images/D1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/D2.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "E": [
    {
      "file": "images/E1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "F": [
    {
      "file": "images/F1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/F2.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "G": [
    {
      "file": "images/G1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "H": [
    {
      "file": "images/H1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "I": [
    {
      "file": "images/I1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "J": [
    {
      "file": "images/J1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "L": [
    {
      "file": "images/L1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "M": [
    {
      "file": "images/M1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/M2.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "N": [
    {
      "file": "images/N1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "O": [
    {
      "file": "images/O1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/O2.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/O3.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "P": [
    {
      "file": "images/P1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    },
    {
      "file": "images/P2.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "Q": [
    {
      "file": "images/Q1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "R": [
    {
      "file": "images/R1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "S": [
    {
      "file": "images/S1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "W": [
    {
      "file": "images/W1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "X": [
    {
      "file": "images/X1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ],
  "Z": [
    {
      "file": "images/Z1.jpg",
      "type": "image",
      "title": "",
      "desc": ""
    }
  ]
};
